apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - my_nfs.yaml
  - my_storage.yaml
  - vaultwarden-deployment.yaml
  - ingress-service.yaml
  - backup.yaml
images:
  - name: vaultwarden
    newTag: "1.34.3"
  - name: debian
    newTag: "12.11"
