#NFS
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vaultwarden-data-pv
spec:
  storageClassName: vaultwarden-data
  capacity:
    storage: 64Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: atsushi.local
    path: /mnt/storage/vaultwarden
  mountOptions:
    - soft
    - timeo=100     # 10秒でタイムアウト（単位は0.1秒）
    - retrans=5    # 5回再試行してダメならエラーを返す