apiVersion: v1
kind: Service
metadata:
  name: desktop-service
  labels:
    app: my-desktop
  # annotations:
  #   metallb.universe.tf/address-pool: custom-addresspool
spec:
  ports:
    - port: 3389
  selector:
    app: my-desktop
  type: LoadBalancer #ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: desktop-setup-script
data:
  setup.sh: |
    #!/bin/bash

    apt-get -y update
    apt-get -y upgrade
    apt-get -y autopurge

    apt-get -y install language-pack-ja-base language-pack-ja
    update-locale LANG=ja_JP.UTF-8 LANGUAGE="ja_JP:ja"
    source /etc/default/locale
    useradd --password "pass" --create-home atsushi
    apt-get -y install sudo
    gpasswd -a atsushi sudo
    DEBIAN_FRONTEND=noninteractive apt-get -y install tzdata
    ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

    # apt-get -y install ubuntu-desktop-minimal task-gnome-desktop task-japanese-gnome-desktop language-pack-gnome-ja-base language-pack-gnome-ja gnome-user-docs-ja fonts-noto-cjk-extra
    apt-get -y install ubuntu-desktop-minimal task-xfce-desktop task-japanese-desktop fonts-noto-cjk-extra

    # systemctl start gdm3
    systemctl start lightdm
    echo "Start Gnome!"

    apt-get -y install xrdp
    systemctl enable xrdp
    echo "Setup Finish!"
    xrdp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: desktop-deployment
  labels:
    app: my-desktop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-desktop
  template:
    metadata:
      labels:
        app: my-desktop
    spec:
      containers:
        - image: ubuntu:jammy #frxyt/xrdp:xfce
          name: desktop
          # env:
          #   - name: "FRX_XRDP_USER_NAME"
          #     value: "atsushi"
          #   - name: "FRX_XRDP_USER_PASSWORD"
          #     value: "pass"
          ports:
            - containerPort: 3389
          volumeMounts:
            - name: desktop-setup-script-file
              mountPath: /usr/local/bin/
          resources:
            limits:
              cpu: 8
              memory: 20Gi
            requests:
              cpu: 6
              memory: 16Gi
          command:
          #  - sleep
          #  - infinity
           - bash
           - /usr/local/bin/setup.sh
            # - sh
            # - "-c"
            # - |
            #   apt-get -y update
            #   apt-get -y upgrade
            #   apt-get -y autopurge
            #   apt-get -y install language-pack-ja-base language-pack-ja
            #   update-locale LANG=ja_JP.UTF-8 LANGUAGE="ja_JP:ja"
            #   source /etc/default/locale
            #   useradd --password "pass" --create-home atsushi
            #   apt-get -y install sudo
            #   gpasswd -a atsushi sudo
            #   DEBIAN_FRONTEND=noninteractive apt-get -y install tzdata
            #   ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
            #   apt-get -y install ubuntu-desktop-minimal task-gnome-desktop task-japanese-gnome-desktop language-pack-gnome-ja-base language-pack-gnome-ja gnome-user-docs-ja fonts-noto-cjk-extra
            #   systemctl start gdm3
            #   echo "Start Gnome!"
            #   apt-get -y install xrdp
            #   systemctl enable xrdp
            #   echo "Setup Finish!"
      volumes:
        - name: desktop-setup-script-file # volumeMountsで/etc/nginxにmountするやつ
          configMap:
            name: desktop-setup-script

