apiVersion: v1
kind: Service
metadata:
  name: desktop-service
  labels:
    app: my-desktop
  # annotations:
  #   metallb.universe.tf/address-pool: custom-addresspool
spec:
  ports:
    - port: 3389
  selector:
    app: my-desktop
  type: LoadBalancer #ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: desktop-deployment
  labels:
    app: my-desktop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-desktop
  template:
    metadata:
      labels:
        app: my-desktop
    spec:
      containers:
        - image: ubuntu:jammy #frxyt/xrdp:xfce
          name: desktop
          # env:
          #   - name: "FRX_XRDP_USER_NAME"
          #     value: "atsushi"
          #   - name: "FRX_XRDP_USER_PASSWORD"
          #     value: "pass"
          ports:
            - containerPort: 3389
          resources:
            limits:
              cpu: 8
              memory: 20Gi
            requests:
              cpu: 6
              memory: 16Gi
          command:
          #  - sleep
          #  - infinity
            - sh
            - "-c"
            - |
              apt -y update
              apt -y upgrade
              apt -y autopurge
              apt -y install language-pack-ja-base language-pack-ja
              update-locale LANG=ja_JP.UTF-8 LANGUAGE="ja_JP:ja"
              source /etc/default/locale
              useradd --password "pass" --create-home atsushi
              apt -y install sudo
              gpasswd -a atsushi sudo
              DEBIAN_FRONTEND=noninteractive apt -y install tzdata
              ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
              apt -y install ubuntu-desktop-minimal task-gnome-desktop task-japanese-gnome-desktop language-pack-gnome-ja-base language-pack-gnome-ja gnome-user-docs-ja fonts-noto-cjk-extra
              apt -y install xrdp
              systemctl enable xrdp
              sleep infinity
