apiVersion: v1
kind: Service
metadata:
  name: desktop-service
  labels:
    app: my-desktop
  # annotations:
  #   metallb.universe.tf/address-pool: custom-addresspool
spec:
  ports:
    - name: xrdp
      port: 3389
    - name: ssh
      port: 22
  selector:
    app: my-desktop
  type: LoadBalancer #ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: desktop-setup-script
data:
  setup.sh: |
    #!/bin/bash

    sed -i -e "s/http\:\/\/archive\.ubuntu\.com\/ubuntu\//http\:\/\/ftp\.udx\.icscoe\.jp\/Linux\/ubuntu\//" /etc/apt/sources.list

    apt-get -y update
    apt-get -y upgrade
    apt-get -y autopurge
    apt-get -y install openssh-server
    /etc/init.d/sshd restart

    apt-get -y install language-pack-ja-base language-pack-ja
    update-locale LANG=ja_JP.UTF-8 LANGUAGE="ja_JP:ja"
    source /etc/default/locale
    DEBIAN_FRONTEND=noninteractive apt-get -y install tzdata
    ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
    apt-get -y install openssl
    useradd --password $(echo "pass" | openssl passwd -1 -stdin) --create-home atsushi
    apt-get -y install sudo
    gpasswd -a atsushi sudo

    apt-get -y install task-xfce-desktop xrdp
    sed -i "s/test -x \/etc\/X11\/Xsession && exec \/etc\/X11\/Xsession/# test -x \/etc\/X11\/Xsession && exec \/etc\/X11\/Xsession/" /etc/xrdp/startwm.sh
    sed -i "s/exec \/bin\/sh \/etc\/X11\/Xsession/# exec \/bin\/sh \/etc\/X11\/Xsession/" /etc/xrdp/startwm.sh
    echo "startxfce4" >> /etc/xrdp/startwm.sh
    /etc/init.d/xrdp restart

    apt-get -y autoclean
    echo "Setup Finish!"
    sleep infinity

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: desktop-deployment
  labels:
    app: my-desktop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-desktop
  template:
    metadata:
      labels:
        app: my-desktop
    spec:
      containers:
        - image: ubuntu:jammy
          name: desktop
          ports:
            - containerPort: 3389
              name: xrdp
            - containerPort: 22
              name: ssh
          volumeMounts:
            - name: desktop-setup-script-file
              mountPath: /usr/local/bin/
          resources:
            limits:
              cpu: 8
              memory: 16Gi
            requests:
              cpu: 8
              memory: 16Gi
          command:
          #  - sleep
          #  - infinity
           - bash
           - /usr/local/bin/setup.sh
            # - sh
            # - "-c"
            # - |
            #   apt-get -y update
            #   apt-get -y upgrade
            #   apt-get -y autopurge
      volumes:
        - name: desktop-setup-script-file
          configMap:
            name: desktop-setup-script

