--- #NFS
apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-mybackup-data-pv
spec:
  storageClassName: drupal-my-backup-data
  capacity:
    storage: 512Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: atsushi.local
    path: /mnt/backup/drupal/data
--- #NFS
apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-mybackup-db-pv
spec:
  storageClassName: drupal-my-backup-db
  capacity:
    storage: 512Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: atsushi.local
    path: /mnt/backup/drupal/db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-backup-data-pv-claim
  labels:
    app: my-drupal-backup-data
spec:
  storageClassName: drupal-my-backup-data
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 512Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-backup-db-pv-claim
  labels:
    app: my-drupal-backup-db-data
spec:
  storageClassName: drupal-my-backup-db
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 512Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-script
data:
  backup.sh: |
    #!/bin/bash

    apt-get -y update
    apt-get -y upgrade
    apt-get -y autopurge
    apt-get -y install rsync
    apt-get -y autoclean

    echo "#####################################################"
    echo "-->  Data Backup !!"

    # Data
    DATADIR="/mnt/data"       #バックアップ元の親ディレクトリ
    BASEDIR="/mnt/backupData" #バックアップ先の親ディレクトリ
    LATESTBKUP=$(ls $BASEDIR | grep backup- | tail -n 1) #直近のバックアップのディレクトリ名
    rsync -Aaxh --link-dest="$BASEDIR/$LATESTBKUP" "$DATADIR/" "$BASEDIR/backup-$(date +%Y%m%d-%H%M%S)"
    # rsync -Aavxh --link-dest="$BASEDIR/$LATESTBKUP" "$DATADIR/" "$BASEDIR/backup-$(date +%Y%m%d-%H%M%S)"

    echo "#####################################################"
    echo "-->  DB Backup !!"

    # DB
    DATADIR="/mnt/db"       #バックアップ元の親ディレクトリ
    BASEDIR="/mnt/backupDb" #バックアップ先の親ディレクトリ
    LATESTBKUP=$(ls $BASEDIR | grep backup- | tail -n 1) #直近のバックアップのディレクトリ名
    rsync -Aaxh --link-dest="$BASEDIR/$LATESTBKUP" "$DATADIR/" "$BASEDIR/backup-$(date +%Y%m%d-%H%M%S)"
    # rsync -Aavxh --link-dest="$BASEDIR/$LATESTBKUP" "$DATADIR/" "$BASEDIR/backup-$(date +%Y%m%d-%H%M%S)"

    echo "#####################################################"

    echo "Backup Finish!"

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: drupal-backup-cronjob
  labels:
    app: my-drupal
spec:
  schedule: "0 3 * * *"
  timeZone: Asia/Tokyo
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup
              image: debian:12.10
              imagePullPolicy: IfNotPresent
              env:
                - name: TZ
                  value: Asia/Tokyo
              command:
                - bash
                - /usr/local/bin/backup.sh
              volumeMounts:
                - name: backup-script-file
                  mountPath: /usr/local/bin/
                #data
                - name: data-persistent-storage
                  mountPath: /mnt/data
                - name: db-persistent-storage
                  mountPath: /mnt/db
                #backup
                - name: backup-data-persistent-storage
                  mountPath: /mnt/backupData
                - name: backup-db-persistent-storage
                  mountPath: /mnt/backupDb
          restartPolicy: OnFailure
          volumes:
            - name: backup-script-file
              configMap:
                name: backup-script
            #data
            - name: data-persistent-storage
              persistentVolumeClaim:
                claimName: drupal-pv-claim
            - name: db-persistent-storage
              persistentVolumeClaim:
                claimName: drupal-mariadb-pv-claim
            #backup
            - name: backup-data-persistent-storage
              persistentVolumeClaim:
                claimName: drupal-backup-data-pv-claim
            - name: backup-db-persistent-storage
              persistentVolumeClaim:
                claimName: drupal-backup-db-pv-claim
