apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets_data.yaml
  - my_nfs.yaml
  - my_storage.yaml
  - mariadb-deployment.yaml
  - drupal-deployment.yaml
  - ingress-service.yaml
  - backup.yaml
images:
  - name: drupal
    newTag: "11.2.3"
  - name: mariadb
    newTag: "11.8"
  - name: debian
    newTag: "12.11"
