apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - name: drupal-mariadb-pass
    literals:
      - root_password=somedrupal
      - database=drupal
      - user=drupal
      - password=drupal
resources:
  - my_nfs.yaml
  - my_storage.yaml
  - mariadb-deployment.yaml
  - drupal-deployment.yaml
  - ingress-service.yaml
  # - backup.yaml
