apiVersion: v1
kind: Service
metadata:
  name: drupal-mariadb-service
  labels:
    app: my-drupal
spec:
  ports:
    - port: 3306
  selector:
    app: my-drupal
    tier: db
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal-mariadb-deployment
  labels:
    app: my-drupal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-drupal
      tier: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: my-drupal
        tier: db
    spec:
      containers:
        - image: mariadb:11.5
          name: mariadb
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: drupal-mariadb-pass
                  key: root_password
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: drupal-mariadb-pass
                  key: password
            - name: MARIADB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: drupal-mariadb-pass
                  key: database
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: drupal-mariadb-pass
                  key: user
            - name: MARIADB_AUTO_UPGRADE
              value: "1"
            - name: MARIADB_DISABLE_UPGRADE_BACKUP
              value: "1"
          ports:
            - containerPort: 3306
              name: mariadb
          args:
            - --character-set-server=utf8
            - --collation-server=utf8_unicode_ci
          volumeMounts:
            - name: drupal-mariadb-persistent-storage
              mountPath: /var/lib/mysql
          resources:
            limits:
              cpu: 2
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
      volumes:
        - name: drupal-mariadb-persistent-storage
          persistentVolumeClaim:
            claimName: drupal-mariadb-pv-claim
