#NFS
apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-data-pv
spec:
  storageClassName: drupal-data
  capacity:
    storage: 128Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: atsushi.local
    path: /mnt/storage/drupal
