#NFS
apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-data-pv
spec:
  storageClassName: drupal-data
  capacity:
    storage: 128Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.128.10 #atsushi.local
    path: /mnt/storage/drupal
  mountOptions:
    - soft
    - timeo=100     # 10秒でタイムアウト（単位は0.1秒）
    - retrans=5    # 5回再試行してダメならエラーを返す