#NFS
apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-my-data-pv
spec:
  storageClassName: drupal-my-data
  capacity:
    storage: 64Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: atsushi.local
    path: /mnt/storage/drupal/data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-my-db-pv
spec:
  storageClassName: drupal-my-db
  capacity:
    storage: 32Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: atsushi.local
    path: /mnt/storage/drupal/db
