#NFS
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mydata-drupal-pv
# spec:
#   storageClassName: my-data-drupal
#   capacity:
#     storage: 64Gi
#   accessModes:
#     - ReadWriteOnce
#   volumeMode: Filesystem
#   persistentVolumeReclaimPolicy: Retain
#   nfs:
#     server: atsushi.local
#     path: /mnt/storage/drupal/data
# ---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mydb-drupal-pv
spec:
  storageClassName: my-db-drupal
  capacity:
    storage: 32Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: atsushi.local
    path: /mnt/storage/drupal/db
---
#############################
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mydata-sites-drupal-pv
spec:
  storageClassName: my-data-drupal-sites
  capacity:
    storage: 32Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: atsushi.local
    path: /mnt/storage/drupal/data/sites
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mydata-themes-drupal-pv
spec:
  storageClassName: my-data-drupal-themes
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: atsushi.local
    path: /mnt/storage/drupal/data/themes
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mydata-modules-drupal-pv
spec:
  storageClassName: my-data-drupal-modules
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: atsushi.local
    path: /mnt/storage/drupal/data/modules
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mydata-profiles-drupal-pv
spec:
  storageClassName: my-data-drupal-profiles
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: atsushi.local
    path: /mnt/storage/drupal/data/profiles
