apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-data-pv-claim
  labels:
    app: my-drupal
spec:
  storageClassName: drupal-data
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 128Gi
