apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-pv-claim
  labels:
    app: my-drupal
spec:
  storageClassName: drupal-my-data
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 64Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-mariadb-pv-claim
  labels:
    app: my-drupal
spec:
  storageClassName: drupal-my-db
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 32Gi
