# addresspool.yaml
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: custom-addresspool
  namespace: metallb-system
spec:
  addresses:
    # - 192.168.3.30-192.168.3.40
    - 192.168.128.30-192.168.128.40
  autoAssign: true
