# addresspool.yaml
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: custom-addresspool
  namespace: metallb-system
spec:
  addresses:
    #-  192.168.43.230-192.168.43.240
    - 192.168.3.100-192.168.3.200
