--- #NFS
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mybackup-data-pv
spec:
  storageClassName: my-backup-data
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: atsushi.local
    path: /mnt/backup/nextcloud/data
--- #NFS
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mybackup-db-pv
spec:
  storageClassName: my-backup-db
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: atsushi.local
    path: /mnt/backup/nextcloud/db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-backup-data-pv-claim
  labels:
    app: my-nextcloud-backup-data
spec:
  storageClassName: my-backup-data
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-backup-db-pv-claim
  labels:
    app: my-nextcloud-backup-db-data
spec:
  storageClassName: my-backup-db
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-script
data:
  backup.sh: |
    #!/bin/bash

    apt-get -y update
    apt-get -y upgrade
    apt-get -y autopurge
    apt-get -y install rsync
    apt-get -y autoclean

    echo "#####################################################"

    # Maintenance mode on
    CONFIGFILEPATH="/mnt/data/config/config.php"
    if grep -q "'maintenance' => false" $CONFIGFILEPATH; then
        echo "Switch maintenance mode!"
        sed -i -e "s/'maintenance' => false/'maintenance' => true/" $CONFIGFILEPATH
    elif grep -q "'maintenance' => true" $CONFIGFILEPATH; then
        echo "Already maintenance mode!"
    else
        echo "NO maintenance!"
        sed -i -e "s/)\;/  'maintenance' => true,\n)\;/" $CONFIGFILEPATH
    fi

    echo "#####################################################"
    echo "-->  Data Backup !!"

    # Data
    DATADIR="/mnt/data"       #バックアップ元の親ディレクトリ
    BASEDIR="/mnt/backupData" #バックアップ先の親ディレクトリ
    LATESTBKUP=$(ls $BASEDIR | grep backup- | tail -n 1) #直近のバックアップのディレクトリ名
    rsync -Aaxh --link-dest="$BASEDIR/$LATESTBKUP" "$DATADIR/" "$BASEDIR/backup-$(date +%Y%m%d-%H%M%S)"
    # rsync -Aavxh --link-dest="$BASEDIR/$LATESTBKUP" "$DATADIR/" "$BASEDIR/backup-$(date +%Y%m%d-%H%M%S)"

    echo "#####################################################"
    echo "-->  DB Backup !!"

    # DB
    DATADIR="/mnt/db"       #バックアップ元の親ディレクトリ
    BASEDIR="/mnt/backupDb" #バックアップ先の親ディレクトリ
    LATESTBKUP=$(ls $BASEDIR | grep backup- | tail -n 1) #直近のバックアップのディレクトリ名
    rsync -Aaxh --link-dest="$BASEDIR/$LATESTBKUP" "$DATADIR/" "$BASEDIR/backup-$(date +%Y%m%d-%H%M%S)"
    # rsync -Aavxh --link-dest="$BASEDIR/$LATESTBKUP" "$DATADIR/" "$BASEDIR/backup-$(date +%Y%m%d-%H%M%S)"

    echo "#####################################################"

    # Maintenance mode off
    sed -i -e "s/'maintenance' => true/'maintenance' => false/" $CONFIGFILEPATH

    echo "Backup Finish!"

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: nextcloud-backup-cronjob
  labels:
    app: my-nextcloud
spec:
  schedule: "0 1 * * *"
  timeZone: Asia/Tokyo
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup
              image: debian:12.8
              imagePullPolicy: IfNotPresent
              env:
                - name: TZ
                  value: Asia/Tokyo
              command:
                - bash
                - /usr/local/bin/backup.sh
              volumeMounts:
                - name: backup-script-file
                  mountPath: /usr/local/bin/
                #data
                - name: data-persistent-storage
                  mountPath: /mnt/data
                - name: db-persistent-storage
                  mountPath: /mnt/db
                #backup
                - name: backup-data-persistent-storage
                  mountPath: /mnt/backupData
                - name: backup-db-persistent-storage
                  mountPath: /mnt/backupDb
          restartPolicy: OnFailure
          volumes:
            - name: backup-script-file
              configMap:
                name: backup-script
            #data
            - name: data-persistent-storage
              persistentVolumeClaim:
                claimName: nextcloud-pv-claim
            - name: db-persistent-storage
              persistentVolumeClaim:
                claimName: mariadb-pv-claim
            #backup
            - name: backup-data-persistent-storage
              persistentVolumeClaim:
                claimName: nextcloud-backup-data-pv-claim
            - name: backup-db-persistent-storage
              persistentVolumeClaim:
                claimName: nextcloud-backup-db-pv-claim
