apiVersion: v1
kind: Service
metadata:
  name: nextcloud-code-service
  labels:
    app: my-nextcloud
  # annotations:
  #   metallb.universe.tf/address-pool: custom-addresspool
spec:
  ports:
    - port: 9980
  selector:
    app: my-nextcloud
    tier: office
  type: ClusterIP
  # clusterIP: None
  # type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-code-deployment
  labels:
    app: my-nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nextcloud
      tier: office
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: my-nextcloud
        tier: office
    spec:
      containers:
        - image: collabora/code:23.05.9.2.1
          name: code
          env:
            - name: password
              value: nextcloud
            - name: username
              value: nextcloud
            ####################
            - name: extra_params
              # value: "--o:ssl.enable=false --o:ssl.termination=false --o:admin_console.username=atsushi --o:admin_console.password=atsushi"
              value: "--o:ssl.enable=false --o:ssl.termination=false"
            - name: server_name
              value: "nextcloud-code-service.default.svc.cluster.local"
          ports:
            - containerPort: 9980
          resources:
            limits:
              cpu: 2
              memory: 2Gi
            requests:
              cpu: 1
              memory: 1Gi

########################
#url
#http://nextcloud-code-service.default.svc.cluster.local:9980