apiVersion: v1
kind: Service
metadata:
  name: cron-nextcloud-service
  labels:
    app: my-nextcloud
spec:
  ports:
    - port: 9000
  selector:
    app: my-nextcloud
    tier: backend
  type: ClusterIP
  # clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cron-nextcloud-deployment
  labels:
    app: my-nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nextcloud
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: my-nextcloud
        tier: backend
  containers:
    - image: nextcloud:25-fpm
      name: nextcloud
      command:
        - /cron.sh
      volumeMounts:
        - name: nextcloud-persistent-storage
          mountPath: /var/www/html
  volumes:
    - name: nextcloud-persistent-storage
      persistentVolumeClaim:
        claimName: nextcloud-pv-claim
