apiVersion: v1
kind: Service
metadata:
  name: cron-nextcloud-service
  labels:
    app: my-nextcloud
  # annotations:
  #   metallb.universe.tf/address-pool: custom-addresspool
spec:
  ports:
    - port: 9000
  selector:
    app: my-nextcloud
    tier: backend
  type: ClusterIP
  # clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cron-nextcloud-deployment
  labels:
    app: my-nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nextcloud
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: my-nextcloud
        tier: backend
    spec:
      containers:
        - image: nextcloud:25-fpm
          name: nextcloud
          command:
            - /cron.sh
          volumeMounts:
            - name: nextcloud-persistent-storage
              mountPath: /var/www/html
          # ###############################
          # ###############################
          # env:
          #   - name: MYSQL_PASSWORD
          #     valueFrom:
          #       secretKeyRef:
          #         name: mariadb-pass
          #         key: password
          #   - name: MYSQL_DATABASE
          #     valueFrom:
          #       secretKeyRef:
          #         name: mariadb-pass
          #         key: database
          #   - name: MYSQL_USER
          #     valueFrom:
          #       secretKeyRef:
          #         name: mariadb-pass
          #         key: user
          #   - name: MYSQL_HOST
          #     value: nextcloud-mariadb-service
          #   - name: REDIS_HOST
          #     value: nextcloud-redis-service
          #   ####################################
          #   - name: NEXTCLOUD_TRUSTED_DOMAINS
          #     value: atsushi.local
          #   - name: OVERWRITEHOST
          #     value: atsushi.local
          #   - name: OVERWRITEPROTOCOL
          #     value: http
          #   - name: OVERWRITEWEBROOT
          #     value: /nc
          #   - name: OVERWRITECLIURL
          #     value: http://atsushi.local/nc
      volumes:
        - name: nextcloud-persistent-storage
          persistentVolumeClaim:
            claimName: nextcloud-pv-claim
