apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # 正規表現を使う
    # nginx.ingress.kubernetes.io/use-regex: "true"
    # 「/」直後から、正規表現のキャプチャしたグループでパスを指定する
    # nginx.ingress.kubernetes.io/rewrite-target: /$2
    # code
    nginx.ingress.kubernetes.io/proxy-read-timeout: 3600
    nginx.ingress.kubernetes.io/proxy-send-timeout: 3600
spec:
  ingressClassName: nginx
  rules:
    # - host: atsushi.local
    - host:
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nextcloud-nginx-service
                port:
                  number: 80
          # - path: /nextcloud(/|$)(.*)
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: nextcloud-nginx-service
          #       port:
          #         number: 80
          # - path: /office(/|$)(.*)
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: nextcloud-code-service
          #       port:
          #         number: 9980
