apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud-ingress
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "false"
    kubernetes.io/tls-acme: "true"
    #
    cert-manager.io/cluster-issuer: "nextcloud-cluster-issuer"
spec:
  ingressClassName: public
  tls:
    - hosts:
        # ドメイン記載
        - nextcloud.oahs.f5.si
        - office.oahs.f5.si
        - test.oahs.f5.si
      secretName: nextcloud-cluster-issuer-secret # cert-managerはこのシークレットに作成した証明書を格納する
  rules:
    - host: atsushi.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nextcloud-nginx-service
                port:
                  number: 80
    - host: nextcloud.oahs.f5.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nextcloud-nginx-service
                port:
                  number: 80
    - host: office.oahs.f5.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nextcloud-office-nginx-service
                port:
                  number: 80
    - host: test.oahs.f5.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: test-nginx-service
                port:
                  number: 80
    - host:
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: test-nginx-service
                port:
                  number: 80
