apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - name: mariadb-pass
    literals:
      - root_password=somenextcloud
      - database=nextcloud
      - user=nextcloud
      - password=nextcloud
  # - name: server-hostname
  #   literals:
  #     - host=100.105.100.72
  #     - root=/nextcloud
  #     - url=http://100.105.100.72/nextcloud
resources:
  # - addresspool.yaml
  - my_nfs.yaml
  - my_strage.yaml
  - redis-deployment.yaml
  - mariadb-deployment.yaml
  - nextcloud-deployment.yaml
  - nginx-deployment.yaml
  - code-deployment.yaml
  - ingress-service.yaml
