apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - name: mariadb-pass
    literals:
      - root_password=somenextcloud
      - database=nextcloud
      - user=nextcloud
      - password=nextcloud
resources:
  - my_nfs.yaml
  - my_storage.yaml
  - redis-deployment.yaml
  - mariadb-deployment.yaml
  - nginx-deployment.yaml
  - nextcloud-deployment.yaml
  - office-nginx-deployment.yaml
  - code-deployment.yaml
  - ingress-service.yaml
  - backup.yaml
