#NFS
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mydata-pv
spec:
  storageClassName: my-data
  capacity:
    storage: 5Ti
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: atsushi.local
    path: /mnt/storage/nfsshare/data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mydb-pv
spec:
  storageClassName: my-db
  capacity:
    storage: 32Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: atsushi.local
    path: /mnt/storage/nfsshare/db