#NFS
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data-pv
spec:
  storageClassName: nextcloud-data
  capacity:
    storage: 512Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.128.10 #atsushi.local
    path: /mnt/storage/nextcloud
  mountOptions:
    - soft
    - timeo=100     # 10秒でタイムアウト（単位は0.1秒）
    - retrans=5    # 5回再試行してダメならエラーを返す