#NFS
#app
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mydata-app-pv
spec:
  storageClassName: my-app
  capacity:
    storage: 64Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: atsushi.local
    path: /mnt/storage/nfsshare/app
---
#db
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mydata-db-pv
spec:
  storageClassName: my-db
  capacity:
    storage: 4Ti
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: atsushi.local
    path: /mnt/storage/nfsshare/db