apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pv-claim
  labels:
    app: my-nextcloud
spec:
  # storageClassName: my-app
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 32Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim
  labels:
    app: my-nextcloud
spec:
  storageClassName: my-db
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Ti
