apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data-pv-claim
  labels:
    app: my-nextcloud
spec:
  storageClassName: nextcloud-data
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 512Gi
