apiVersion: v1
kind: Service
metadata:
  name: nextcloud-service
  labels:
    app: my-nextcloud
spec:
  ports:
    - port: 9000
      # targetPort: 9000
      # protocol: TCP
  selector:
    app: my-nextcloud
    tier: backend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-deployment
  labels:
    app: my-nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nextcloud
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: my-nextcloud
        tier: backend
    spec:
      containers:
        - image: nextcloud:29-fpm
          name: nextcloud
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-pass
                  key: password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mariadb-pass
                  key: database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-pass
                  key: user
            - name: MYSQL_HOST
              value: nextcloud-mariadb-service
            - name: REDIS_HOST
              value: nextcloud-redis-service
            ####################################
            - name: NEXTCLOUD_ADMIN_USER
              value: atsushi
            - name: NEXTCLOUD_ADMIN_PASSWORD
              value: odake
            ####################################
            # - name: NEXTCLOUD_UPDATE
            #   value: "1"
            # - name: NEXTCLOUD_INIT_LOCK
            #   value: "true"
            # - name: NEXTCLOUD_INIT_HTACCESS
            #   value: "true"
            - name: PHP_MEMORY_LIMIT
              value: 1G
            ####################################
            - name: TRUSTED_PROXIES
              value: "10.152.183.0/24" #gethostbyname("nextcloud-nginx-service")
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: "'atsushi.local' 'nextcloud.oahs.f5.si' '100.105.100.72'"
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: nextcloud-persistent-storage
              mountPath: /var/www/html
          resources:
            limits:
              cpu: 2
              memory: 6Gi
            requests:
              cpu: 1
              memory: 3Gi
        - image: nextcloud:29-fpm
          name: cron-nextcloud
          command:
            - /cron.sh
          volumeMounts:
            - name: nextcloud-persistent-storage
              mountPath: /var/www/html
          resources:
            limits:
              cpu: 1
              memory: 4Gi
            requests:
              cpu: 500m
              memory: 2Gi
      volumes:
        - name: nextcloud-persistent-storage
          persistentVolumeClaim:
            claimName: nextcloud-pv-claim
