apiVersion: v1
kind: Service
metadata:
  name: nextcloud-service
  labels:
    app: my-nextcloud
spec:
  ports:
    - port: 9000
  selector:
    app: my-nextcloud
    tier: backend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-deployment
  labels:
    app: my-nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nextcloud
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: my-nextcloud
        tier: backend
    spec:
      containers:
        - image: nextcloud:27-fpm
          name: nextcloud
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-pass
                  key: password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mariadb-pass
                  key: database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-pass
                  key: user
            - name: MYSQL_HOST
              value: nextcloud-mariadb-service
            - name: REDIS_HOST
              value: nextcloud-redis-service
            ####################################
            - name: TRUSTED_PROXIES
              value: nextcloud-nginx-service
            # - name: NEXTCLOUD_TRUSTED_DOMAINS
            #   value: atsushi.local
            - name: OVERWRITEHOST
              # value: atsushi.local
              valueFrom:
                secretKeyRef:
                  name: server-hostname
                  key: host
            - name: OVERWRITEPROTOCOL
              value: http
            - name: OVERWRITEWEBROOT
              # value: /nextcloud
              valueFrom:
                secretKeyRef:
                  name: server-hostname
                  key: root
            - name: OVERWRITECLIURL
              # value: http://atsushi.local/nextcloud
              valueFrom:
                secretKeyRef:
                  name: server-hostname
                  key: url
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: nextcloud-persistent-storage
              mountPath: /var/www/html
          resources:
            limits:
              cpu: 2
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
        - image: nextcloud:27-fpm
          name: cron-nextcloud
          command:
            - /cron.sh
          volumeMounts:
            - name: nextcloud-persistent-storage
              mountPath: /var/www/html
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 512Mi
      volumes:
        - name: nextcloud-persistent-storage
          persistentVolumeClaim:
            claimName: nextcloud-pv-claim
