apiVersion: v1
kind: Service
metadata:
  name: nextcloud-service
  labels:
    app: my-nextcloud
spec:
  ports:
    - port: 9000
      # targetPort: 9000
      # protocol: TCP
  selector:
    app: my-nextcloud
    tier: backend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-deployment
  labels:
    app: my-nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nextcloud
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: my-nextcloud
        tier: backend
    spec:
      containers:
        - image: nextcloud:30.0.5-fpm
          name: nextcloud
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-mariadb-pass
                  key: password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: nextcloud-mariadb-pass
                  key: database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud-mariadb-pass
                  key: user
            - name: MYSQL_HOST
              value: nextcloud-mariadb-service
            - name: REDIS_HOST
              value: nextcloud-redis-service
            ####################################
            - name: NEXTCLOUD_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud-admin-user
                  key: user
            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-admin-user
                  key: password
            ####################################
            # - name: NEXTCLOUD_UPDATE
            #   value: "1"
            # - name: NEXTCLOUD_INIT_LOCK
            #   value: "true"
            - name: NEXTCLOUD_INIT_HTACCESS
              value: "true"
            - name: PHP_MEMORY_LIMIT
              value: 8G
            - name: PHP_UPLOAD_LIMIT
              value: 5G
            ####################################
            - name: TRUSTED_PROXIES
              value: "10.152.183.0/24 10.1.174.0/24 100.64.0.0/10" #service,pod,tailscale
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: "'atsushi.local' 'nextcloud.oahs.f5.si'"
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: nextcloud-persistent-storage
              mountPath: /var/www/html
            - name: post-upgrade-script-file
              mountPath: /docker-entrypoint-hooks.d/post-upgrade/
            - name: post-installation-script-file
              mountPath: /docker-entrypoint-hooks.d/post-installation/
          resources:
            limits:
              cpu: "3"
              memory: 12Gi
            requests:
              cpu: "2"
              memory: 8Gi
        - image: nextcloud:30.0.5-fpm
          name: cron-nextcloud
          command:
            - /cron.sh
          volumeMounts:
            - name: nextcloud-persistent-storage
              mountPath: /var/www/html
          resources:
            limits:
              cpu: "500"
              memory: 1Gi
            requests:
              cpu: "256m"
              memory: 512Mi
      volumes:
        - name: nextcloud-persistent-storage
          persistentVolumeClaim:
            claimName: nextcloud-pv-claim
        - name: post-upgrade-script-file
          configMap:
            name: post-upgrade-script
            items:
              - key: post-upgrade.sh
                path: post-upgrade.sh
                mode: 0755
        - name: post-installation-script-file
          configMap:
            name: post-installation-script
            items:
              - key: post-installation.sh
                path: post-installation.sh
                mode: 0755
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: post-upgrade-script
data:
  post-upgrade.sh: |
    #!/bin/bash

    php occ maintenance:mode --on
    php occ config:system:set default_timezone --value="Asia/Tokyo"
    php occ config:system:set maintenance_window_start --type=integer --value=1
    php occ config:system:set default_phone_region --value="JP"
    php occ files:scan --all
    php occ groupfolders:scanl --all
    php occ maintenance:repair --include-expensive
    php occ db:add-missing-indices
    php occ maintenance:mode --off

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: post-installation-script
data:
  post-installation.sh: |
    #!/bin/bash

    php occ maintenance:mode --on
    php occ config:system:set default_timezone --value="Asia/Tokyo"
    php occ config:system:set maintenance_window_start --type=integer --value=1
    php occ config:system:set default_phone_region --value="JP"
    php occ files:scan --all
    php occ groupfolders:scanl --all
    php occ maintenance:repair --include-expensive
    php occ db:add-missing-indices
    php occ maintenance:mode --off

# ls /var/www/html/ | grep -v -E 'data|custom_apps|themes' | xargs rm -rf
# su www-data -s /bin/bash  -c "php occ config:system:set default_timezone --value='Asia/Tokyo'"
# truncate --size 0 /var/www/html/data/nextcloud.log
