apiVersion: v1
kind: Service
metadata:
  name: nextcloud-code-nginx-service
  labels:
    app: my-nextcloud
spec:
  ports:
    - port: 80
  selector:
    app: my-nextcloud
    tier: office
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-code-nginx-conf
data:
  code.conf: |
    upstream code_server {
        server nextcloud-code-service:9980;
    }

    server {
      listen 80;

      # static files
      location ^~ /browser {
        proxy_pass http://code_server;
        proxy_set_header Host $http_host;
      }

      # WOPI discovery URL
      location ^~ /hosting/discovery {
        proxy_pass http://code_server;
        proxy_set_header Host $http_host;
      }

      # Capabilities
      location ^~ /hosting/capabilities {
        proxy_pass http://code_server;
        proxy_set_header Host $http_host;
      }

      # main websocket
      location ~ ^/cool/(.*)/ws$ {
        proxy_pass http://code_server;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $http_host;
        proxy_read_timeout 36000s;
      }

      # download, presentation and image upload
      location ~ ^/(c|l)ool {
        proxy_pass http://code_server;
        proxy_set_header Host $http_host;
      }

      # Admin Console websocket
      location ^~ /cool/adminws {
        proxy_pass http://code_server;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $http_host;
        proxy_read_timeout 36000s;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-code-nginx-deployment
  labels:
    app: my-nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nextcloud
      tier: office
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: my-nextcloud
        tier: office
    spec:
      containers:
        - image: nginx:stable
          name: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nextcloud-code-nginx-config
              mountPath: /etc/nginx/conf.d/
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: nextcloud-code-nginx-config # volumeMountsで/etc/nginxにmountするやつ
          configMap:
            name: nextcloud-code-nginx-conf # ConfigMapのnginx-confを/etc/nginx以下に配置する
