apiVersion: v1
kind: Service
metadata:
  name: nextcloud-office-service
  labels:
    app: my-nextcloud
spec:
  ports:
    - port: 9980
  selector:
    app: my-nextcloud
    tier: office
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-office-deployment
  labels:
    app: my-nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nextcloud
      tier: office
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: my-nextcloud
        tier: office
    spec:
      containers:
        - image: collabora/code:24.04.12.2.1
          name: office
          env:
            - name: password
              value: nextcloud
            - name: username
              value: nextcloud
            ####################
            - name: extra_params
              value: "--o:ssl.enable=false --o:ssl.termination=true"
          ports:
            - containerPort: 9980
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
            requests:
              cpu: "1"
              memory: 2Gi
########################
#設定用url
#https://office.oahs.f5.si/browser/dist/admin/admin.html
