apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: nextcloud-traefik-config
spec:
  forwardingTimeouts:
    # 接続が確立するまでの待ち時間
    dialTimeout: 3600s
    # レスポンスヘッダーが返ってくるまでの待ち時間（生成AIではここが重要）
    responseHeaderTimeout: 3600s
    # アイドル状態の接続を保持する時間
    idleConnTimeout: 3600s
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: nextcloud-buffering-middleware
  namespace: default
spec:
  buffering:
      # リクエストボディの最大サイズ (32GB)
      maxRequestBodyBytes: 34359738368
      # メモリ上にキャッシュする最大サイズ (32GB)
      maxResponseBodyBytes: 34359738368