apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - my_nfs.yaml
  - my_storage.yaml
  - ollama-deployment.yaml
  - searxng-deployment.yaml
  - OpenWebUI-deployment.yaml
  - traefik_config.yaml
  - ingress-service.yaml

images:
  - name: ollama/ollama
    newTag: "0.32.5"
  - name: ghcr.io/open-webui/open-webui
    newTag: "v0.11.0"
  - name: searxng/searxng
    newTag: "2026.7.28-c01178d03"
