# NFS
# ollama
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-data-pv
spec:
  storageClassName: ollama-data
  capacity:
    storage: 128Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: atsushi.local
    path: /home/atsushi/ollama_data #/mnt/storage/ollama
---
# NFS
# OpenWebUI
apiVersion: v1
kind: PersistentVolume
metadata:
  name: open-webui-data-pv
spec:
  storageClassName: open-webui-data
  capacity:
    storage: 64Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: atsushi.local
    path: /mnt/storage/OpenWebUI
