# Ollama
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pv-claim
  labels:
    app: my-AI
spec:
  storageClassName: ollama-data
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 64Gi
---
#Open Web UI
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-data-pv-claim
  labels:
    app: my-AI
spec:
  storageClassName: open-webui-data
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 32Gi
