# Ollama
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pv-claim
  labels:
    app: my-AI
spec:
  storageClassName: my-llm
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 64Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-pv
spec:
  storageClassName: my-llm
  capacity:
    storage: 64Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "~/LLM_data"
---
#Open Web UI
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-pv-claim
  labels:
    app: my-AI
spec:
  storageClassName: my-open-webui
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: open-webui-pv
spec:
  storageClassName: my-open-webui
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "~/OpenWebUI_data"
