apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  labels:
    app: my-AI
spec:
  ports:
    - port: 11434
  selector:
    app: my-AI
    tier: backend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-deployment
  labels:
    app: my-AI
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-AI
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: my-AI
        tier: backend
    spec:
      containers:
        - image: ollama/ollama:0.5.4
          name: ollama
          ports:
            - containerPort: 11434
          resources:
            limits:
              cpu: "4"
              memory: 32Gi
            requests:
              cpu: "2"
              memory: 8Gi
