apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  labels:
    app: my-AI-ollama
spec:
  ports:
    - port: 11434
      targetPort: 11434
  selector:
    app: my-AI-ollama
    tier: backend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-deployment
  labels:
    app: my-AI
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-AI-ollama
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: my-AI-ollama
        tier: backend
    spec:
      initContainers:
        - image: ollama/ollama:latest
          name: init-ollama-model-download
          command: ["/bin/bash", "-c"]
          args:
            - |
              # バックグラウンドでollamaサーバーを起動
              ollama serve &

              # サーバーが起動するまで待つ (ヘルスチェック)
              until ollama list > /dev/null 2>&1; do
                echo "Waiting for ollama server to start..."
                sleep 2
              done

              # 目的のモデルをプルする
              echo "Pulling model..."
              ollama pull gemma4:26b
              ollama pull qwen3.6:35b
              ollama pull embeddinggemma:300m
              ollama pull qwen3-embedding:0.6b
              ollama pull qwen2.5-coder:1.5b

              # プルが完了したら、バックグラウンドのサーバーを終了して正常終了させる
              echo "Model pull complete. Shutting down init server."
              pkill ollama
          volumeMounts:
            - name: ollama-persistent-storage
              mountPath: /root/.ollama
      containers:
        - image: ollama/ollama:latest
          name: ollama
          env:
            - name: OLLAMA_NUM_THREADS
              value: "11"
            - name: OLLAMA_MAX_LOADED_MODELS
              value: "2"
          ports:
            - containerPort: 11434
          volumeMounts:
            - name: ollama-persistent-storage
              mountPath: /root/.ollama
          resources:
            limits:
              cpu: "11" #"14"
              memory: 40Gi
            requests:
              cpu: "11" #"12"
              memory: 40Gi #16Gi
      volumes:
        - name: ollama-persistent-storage
          persistentVolumeClaim:
            claimName: ollama-pv-claim