apiVersion: v1
kind: Service
metadata:
  name: open-webui-service
  labels:
    app: my-AI-open-webui
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: my-AI-open-webui
    tier: backend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui-deployment
  labels:
    app: my-AI-open-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-AI-open-webui
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: my-AI-open-webui
        tier: backend
    spec:
      containers:
        - image: ghcr.io/open-webui/open-webui:main
          name: open-webui
          env:
            - name: OLLAMA_BASE_URL
              value: "http://ollama-service:11434" #"https://ollama.oahs.f5.si"
            - name: DEFAULT_MODELS
              value: "gemma4:26b"
            - name: ENABLE_WEB_SEARCH
              value: "True"
            - name: WEB_SEARCH_ENGINE
              value: "searxng"
            - name: ENABLE_RAG_WEB_SEARCH
              value: "True"
            - name: ENABLE_RAG_LOCAL_WEB_FETCH
              value: "True"
            - name: RAG_EMBEDDING_ENGINE
              value: "ollama"
            - name: RAG_EMBEDDING_MODEL
              value: "embeddinggemma:300m"
            - name: RAG_OLLAMA_BASE_URL
              value: "http://ollama-service:11434" #"https://ollama.oahs.f5.si"
            - name: RAG_TEXT_SPLITTER
              value: "token"
            - name: CHUNK_SIZE
              value: "600"
            - name: CHUNK_OVERLAP
              value: "60"
            # - name: "ENABLE_RAG_HYBRID_SEARCH"
            #   value: "True"
            # - name: "RAG_RERANKING_MODEL"
            #   value: "cl-nagoya/ruri-v3-reranker-310m" # "hotchpotch/japanese-reranker-xsmall-v2" #"qllama/bge-reranker-v2-m3:q4_k_m"
            - name: RAG_WEB_SEARCH_ENGINE
              value: "searxng"
            - name: SEARXNG_QUERY_URL
              value: "http://searxng-service:8888/search?q=docker&format=json"
              # value: "https://search.oahs.f5.si/search?q=<query>&format=json"
              # value: "https://search.oahs.f5.si/search?lang=ja&q=<query>"
            # - name: BYPASS_WEB_SEARCH_EMBEDDING_AND_RETRIEVAL
            #   value: "True"
            # - name: WEB_SEARCH_TRUST_ENV
            #   value: "True"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: open-webui-persistent-storage
              mountPath: /app/backend/data
          resources:
            limits:
              cpu: "1"
              memory: 6Gi
            requests:
              cpu: "1"
              memory: 6Gi
      volumes:
        - name: open-webui-persistent-storage
          persistentVolumeClaim:
            claimName: open-webui-data-pv-claim
