apiVersion: v1
kind: Service
metadata:
  name: searxng-service
  labels:
    app: my-SearXNG
spec:
  ports:
    - port: 8888
      targetPort: 8080
  selector:
    app: my-SearXNG
    tier: backend
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-settings
data:
  settings.yml: |
    use_default_settings: true
    search:
      formats:
        - html
        - json
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: searxng-deployment
  labels:
    app: my-SearXNG
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-SearXNG
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: my-SearXNG
        tier: backend
    spec:
      containers:
        - image: searxng/searxng:2025.4.27-c733aa83e
          name: searxng
          env:
            - name: BASE_URL
              value: "https://searxng.oahs.f5.si"
          ports:
            - containerPort: 8080
          # volumeMounts:
          #   - name: open-webui-persistent-storage
          #     mountPath: /app/backend/data
          volumeMounts:
            - name: searxng-settings-file
              mountPath: /usr/local/searxng/settings.yml
              subPath: settings.yml
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: "500m"
              memory: 1Gi
      # volumes:
      #   - name: open-webui-persistent-storage
      #     persistentVolumeClaim:
      #       claimName: open-webui-pv-claim
      volumes:
        - name: searxng-settings-file # volumeMountsで/etc/nginxにmountするやつ
          configMap:
            name: searxng-settings # ConfigMapのnginx-confを/etc/nginx以下に配置する
