apiVersion: v1
kind: Service
metadata:
  name: searxng-service
  labels:
    app: my-SearXNG
spec:
  ports:
    - port: 8888
      targetPort: 8080
  selector:
    app: my-SearXNG
    tier: backend
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-settings
data:
  settings.yml: |
    use_default_settings: true
    search:
      formats:
        - html
        - json
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: searxng-deployment
  labels:
    app: my-SearXNG
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-SearXNG
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: my-SearXNG
        tier: backend
    spec:
      containers:
        - image: searxng/searxng:2025.4.27-c733aa83e
          name: searxng
          # command:
          #   - "/bin/ash"
          # args:
          #   - "-c"
          #   - >
          #     sed -i s/"- html"/"- html\n    - json\n"/g /etc/searxng/settings.yml &&
          #     sed -i s/"request_timeout: 3.0"/"request_timeout: 10.0"/g /etc/searxng/settings.yml
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/ash"
                  - "-c"
                  - >
                    cp -n /etc/searxng/settings.yml /etc/searxng/settings_default.yml &&
                    sed -i s/"- html"/"- html\n    - json\n"/g /etc/searxng/settings.yml &&
                    sed -i s/"request_timeout: 3.0"/"request_timeout: 10.0"/g /etc/searxng/settings.yml
          env:
            - name: BASE_URL
              value: "https://searxng.oahs.f5.si"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: searxng-persistent-storage
              mountPath: /etc/searxng
            # - name: searxng-settings-file
            #   mountPath: /usr/local/searxng/settings.yml
            #   subPath: settings.yml
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: "500m"
              memory: 1Gi
      volumes:
        - name: searxng-persistent-storage
          persistentVolumeClaim:
            claimName: searxng-pv-claim
        - name: searxng-settings-file # volumeMountsで/etc/nginxにmountするやつ
          configMap:
            name: searxng-settings # ConfigMapのnginx-confを/etc/nginx以下に配置する
