apiVersion: v1
kind: Service
metadata:
  name: searxng-service
  labels:
    app: my-AI
spec:
  ports:
    - port: 808080
      targetport: 8080
  selector:
    app: my-AI
    tier: backend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: searxng-deployment
  labels:
    app: my-AI
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-AI
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: my-AI
        tier: backend
    spec:
      containers:
        - image: searxng/searxng:2025.4.27-c733aa83e
          name: searxng
          # env:
          #   - name: OLLAMA_BASE_URL
          #     value: "http://ollama-service.default.svc.cluster.local:11434"
          ports:
            - containerPort: 8080
          # volumeMounts:
          #   - name: open-webui-persistent-storage
          #     mountPath: /app/backend/data
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: "500m"
              memory: 1Gi
      # volumes:
      #   - name: open-webui-persistent-storage
      #     persistentVolumeClaim:
      #       claimName: open-webui-pv-claim
