---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openwebui-secret-key
  namespace: default
spec:
  encryptedData:
    secret_key: AgBaAdUmHG0IgXfYSXX8DcqiL4kXilV2A9rAtLYzrF/0Ypz9NPuFNrSiqOybvYXKdzw5nzyEGWzmAGaiNigD//t+dLdDBn3sPeytU+psGgs+ApC6Q6U20ALgXyRMLm8T1t51jaB+TyRiIfrsCGxAMJ5ZijP99SwqAWBWwMy2dc4j/S9jF6E2MQLrNjdQQXWgK4l9wqHRDOFW6hWY35mb3Sdr8mr70T8Scv8U2qmB71FMajdMKmVWDdH3RQGdaCur+ZgoSYt0N6AwA0uTGM3YrQCWd2X0+oxPV8qLYDOvoIC1nmSYZB+tOylnl+NGNNC47nd1sMnnMwftfCTXJYP8LLCTRZ7c1VA/kj7md2YVU7ha8rX1TZbU/XKEnQz1FaiGshiyRJQPAN/H/4EltI/KYU/y2tkgcb8f5BWwMwUPajq499EPhJHUFKmRQFjWD2wiiIuhELKsXwV7sAiMbrD8xuX8vqAIdl/0Npfagy5Xg85vDpjEYxeZJJh03e8ez2d6PPOcn/CNCmaUJvhaTP8nz6Ftt93LVDVQA9m0kBb1lqukpDH8S/09KlQPk4uu4uXojz0CVRDjr1bZ9wJp/1gDHHuZb6o+AKcLWK2E2Ji+JFHWlPum8Z1NmaNDUFAO62BaDEMHXTdh8QccfBluafaOFUzbFBIBYUII/PUfs0+OQafPnjZrzjL2T+9/3AXPDUX8kPlxa2Es3WsXD20=
  template:
    metadata:
      name: openwebui-secret-key
      namespace: default
    type: Opaque
